#!/usr/bin/env bash
set -e

TL=${1:-1500}
MATCHING_TL=${2:-60}
CANDIDATES=${3:-60}
MATCHING_RANDOM_FALLBACK_TRIALS=${4:-2048}
WINDOW_PERM_TL=${5:-300}
WINDOW_PERM_MEAN_SIZE=${6:-5}
WINDOW_PERM_MAX_SIZE=${7:-10}

g++ -O3 -std=c++17 solver.cpp -o solver

TSP_TIME_LIMIT="$TL" \
TSP_MATCHING_ANNEAL_TIME_LIMIT="$MATCHING_TL" \
TSP_CANDIDATES="$CANDIDATES" \
TSP_MATCHING_RANDOM_FALLBACK_TRIALS="$MATCHING_RANDOM_FALLBACK_TRIALS" \
TSP_WINDOW_PERM_TIME_LIMIT="$WINDOW_PERM_TL" \
TSP_WINDOW_PERM_MEAN_SIZE="$WINDOW_PERM_MEAN_SIZE" \
TSP_WINDOW_PERM_MAX_SIZE="$WINDOW_PERM_MAX_SIZE" \
./solver data "$TL"